packages:
- .

extra-deps:
- text-format-0.3.2
- Diff-0.3.4
# - liquid-fixpoint-0.8.10.2
# - liquidhaskell-0.8.10.1
# - liquid-base-4.14.1.0
# - liquid-ghc-prim-0.6.1

- git: https://github.com/ucsd-progsys/liquidhaskell
  commit: 892552d4e7177da1135a157624363a8d5107c623
  subdirs:
    - .
    - liquid-base
    - liquid-ghc-prim
    - liquid-containers
    - liquid-prelude
- git: https://github.com/ucsd-progsys/liquid-fixpoint
  commit: d34add2bb85a3edfd905acbd32cec29f55409c75


resolver: nightly-2020-10-03